#![deny(unsafe_code)]
//! Crate root. `unsafe` is denied globally; `fdw::scan` and `fdw::modify`
//! carve themselves out via `#[allow(unsafe_code)]` (they are the FFI
//! boundary to Postgres' executor and additionally enable
//! `deny(unsafe_op_in_unsafe_fn)` so each unsafe op is still individually
//! opted into). `fdw::build_routine` also opts in for the single
//! `alloc_node` call. Every other module remains free of `unsafe`.

pub mod azure;
pub mod convert;
pub mod error;
pub mod fdw;
pub mod parquet_io;
pub mod redact;
pub mod runtime;

#[cfg(feature = "pg_test")]
pub mod test_harness;

use pgrx::prelude::*;

pgrx::pg_module_magic!();

/// PG backend init hook. Runs once per backend (after `pg_module_magic!`
/// registers the library). We use it to register our `XactCallback` for
/// staging-blob cleanup on transaction abort — see
/// `fdw::modify::coordinator::install_xact_callback_once`.
#[pg_guard]
extern "C-unwind" fn _PG_init() {
    crate::fdw::modify::coordinator::install_xact_callback_once();
}

/// FDW handler — returns an `FdwRoutine` populated with our callbacks.
/// pgrx maps the `PgBox<FdwRoutine>` return into PG's `fdw_handler` type, so
/// no custom `sql=` override is needed: the generated `CREATE FUNCTION` will
/// already say `RETURNS fdw_handler`.
#[pg_extern]
fn parquet_azure_fdw_handler() -> PgBox<pg_sys::FdwRoutine, pgrx::AllocatedByRust> {
    fdw::build_routine()
}

/// FDW validator — invoked by PG for every `CREATE/ALTER SERVER`,
/// `USER MAPPING`, or `FOREIGN TABLE` against this wrapper. We hand the raw
/// `text[]` straight to [`fdw::options::validate`] which dispatches by
/// catalog OID to the matching parser; any [`error::FdwError`] is reraised
/// as a PG `ERROR`.
#[pg_extern]
fn parquet_azure_fdw_validator(options: Vec<Option<String>>, catalog: pg_sys::Oid) {
    if let Err(e) = fdw::options::validate(options, catalog) {
        crate::error::raise(e);
    }
}

// Create the FDW itself. The handler/validator CREATE FUNCTION lines are
// auto-generated by pgrx from the `#[pg_extern]` attributes above, so we
// only need to wire them into a FOREIGN DATA WRAPPER.
extension_sql!(
    r#"
    CREATE FOREIGN DATA WRAPPER parquet_azure_fdw
        HANDLER parquet_azure_fdw_handler
        VALIDATOR parquet_azure_fdw_validator;
    "#,
    name = "parquet_azure_fdw_bootstrap",
    requires = [parquet_azure_fdw_handler, parquet_azure_fdw_validator],
);

#[cfg(any(test, feature = "pg_test"))]
#[pgrx::pg_schema]
mod tests {
    use pgrx::prelude::*;

    #[pg_test]
    fn smoke() {
        assert_eq!(Spi::get_one::<i32>("SELECT 1").unwrap(), Some(1));
    }

    /// Verify the extension loads cleanly and that the FDW handler +
    /// validator are usable for a real `CREATE SERVER` (without touching
    /// Azure — the validator only sanity-checks options).
    #[pg_test]
    fn extension_loads() {
        Spi::run(
            r#"CREATE SERVER s_load FOREIGN DATA WRAPPER parquet_azure_fdw
                 OPTIONS (account_name 'acct', auth_method 'managed_identity')"#,
        )
        .unwrap();
    }

    // ---------------------------------------------------------------------
    // End-to-end SELECT suite (Task 16).
    //
    // Each `#[pg_test]` here exercises the full FDW path: an in-memory
    // wiremock-backed `FakeBlobStore` holds parquet fixtures we author
    // in-process via [`ParquetBatchWriter`]; PostgreSQL talks to the FDW
    // via `CREATE FOREIGN TABLE`, the FDW resolves a SAS URL against the
    // fake, fetches the parquet bytes, and feeds row batches up through
    // `IterateForeignScan`.
    //
    // Auth note: v1 only supports `auth_method = 'sas_url'`. The fake
    // ignores the query string of the SAS URL — any URL pointing at the
    // mock server is accepted.
    //
    // Pushdown caveat: Task 11 left qual-pushdown stubbed (no row-group
    // pruning), so the `row_group_pruning_skips_groups` case only asserts
    // PG-level WHERE correctness. Once T11 grows real predicate pushdown,
    // an EXPLAIN check that the FDW reports fewer `rows_processed` becomes
    // meaningful.
    #[cfg(feature = "pg_test")]
    use crate::test_harness::{build_multi_rowgroup_parquet, build_simple_parquet, FakeBlobStore};

    /// Boilerplate SQL that wires Server, UserMapping, and ForeignTable for
    /// `container` against a single blob (or glob pattern) `filename`. The
    /// `endpoint` SERVER option is a placeholder for the SasUrl auth path —
    /// the full pre-signed URL on the user mapping carries everything the
    /// SDK needs to reach the fake.
    #[cfg(feature = "pg_test")]
    fn install_objects_sql(
        suffix: &str,
        fake: &FakeBlobStore,
        container: &str,
        filename: &str,
    ) -> String {
        let sas = fake.sas_url(container);
        format!(
            r#"
            DROP FOREIGN TABLE IF EXISTS events_{suffix} CASCADE;
            DROP USER MAPPING IF EXISTS FOR CURRENT_USER SERVER az_{suffix};
            DROP SERVER IF EXISTS az_{suffix} CASCADE;

            CREATE SERVER az_{suffix} FOREIGN DATA WRAPPER parquet_azure_fdw
              OPTIONS (account_name 'fakeaccount',
                       endpoint 'blob.core.windows.net',
                       auth_method 'sas_url');
            CREATE USER MAPPING FOR CURRENT_USER SERVER az_{suffix}
              OPTIONS (sas_url '{sas}');
            CREATE FOREIGN TABLE events_{suffix} (id bigint, name text)
              SERVER az_{suffix}
              OPTIONS (container '{container}', filename '{filename}');
            "#
        )
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn select_single_blob() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-select-single";
        let bytes = build_simple_parquet(&[1, 2, 3, 4], &["a", "b", "c", "d"]);
        fake.put_blob(container, "events.parquet", bytes);

        Spi::run(&install_objects_sql(
            "single",
            &fake,
            container,
            "events.parquet",
        ))
        .expect("install foreign objects");

        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_single")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 4, "expected 4 rows from single blob");

        let max_id = Spi::get_one::<i64>("SELECT MAX(id) FROM events_single")
            .expect("max query")
            .expect("max not null");
        assert_eq!(max_id, 4);
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn projection_only_selects_one_column() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-select-proj";
        let bytes = build_simple_parquet(&[10, 20, 30, 40], &["w", "x", "y", "z"]);
        fake.put_blob(container, "events.parquet", bytes);

        Spi::run(&install_objects_sql(
            "proj",
            &fake,
            container,
            "events.parquet",
        ))
        .expect("install foreign objects");

        // v1 pushdown stub: projection list is forwarded to the parquet
        // reader via `tts_values`; we don't assert on EXPLAIN output and
        // only check correctness.
        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM (SELECT id FROM events_proj) s")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 4);

        let sum_ids = Spi::get_one::<i64>("SELECT SUM(id)::bigint FROM events_proj")
            .expect("sum query")
            .expect("sum not null");
        assert_eq!(sum_ids, 100);
    }

    /// Phase C — explicit column-projection coverage. `SELECT name FROM t`
    /// should fetch the `name` column from parquet (not all of them) AND
    /// the result should still be correct row-for-row. The previous
    /// `projection_only_selects_one_column` test only asserted that the
    /// scan completes; this one verifies the projected values themselves
    /// match the source so we'd notice if the attno_map shifted (e.g. a
    /// regression that fills the wrong slot position).
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn select_only_name_column_returns_correct_values() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-proj-name";
        let bytes = build_simple_parquet(&[10, 20, 30], &["alpha", "beta", "gamma"]);
        fake.put_blob(container, "events.parquet", bytes);

        Spi::run(&install_objects_sql(
            "projname",
            &fake,
            container,
            "events.parquet",
        ))
        .expect("install foreign objects");

        // Only the `name` column is in reltarget → projection = [name].
        // Iterate must put `name` at relation attnum 2 (slot index 1),
        // and `id` at slot index 0 must remain NULL (PG won't read it).
        let names: Vec<Option<String>> = (1..=3)
            .map(|i| {
                Spi::get_one::<String>(&format!(
                    "SELECT name FROM events_projname ORDER BY name LIMIT 1 OFFSET {}",
                    i - 1
                ))
                .expect("select name")
            })
            .collect();
        let unwrapped: Vec<String> = names.into_iter().map(|o| o.unwrap()).collect();
        assert_eq!(unwrapped, vec!["alpha", "beta", "gamma"]);
    }

    /// Phase C — count(*) edge case. `SELECT count(*) FROM t` references
    /// zero Var columns; `get_foreign_plan` must fall back to projecting
    /// column 0 so the parquet reader has something to iterate. Asserts
    /// the count is correct against the seeded row count.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn select_count_star_works_with_zero_column_projection() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-proj-count";
        let bytes = build_simple_parquet(&[1, 2, 3, 4, 5], &["a", "b", "c", "d", "e"]);
        fake.put_blob(container, "events.parquet", bytes);

        Spi::run(&install_objects_sql(
            "projcount",
            &fake,
            container,
            "events.parquet",
        ))
        .expect("install foreign objects");

        let n = Spi::get_one::<i64>("SELECT count(*)::bigint FROM events_projcount")
            .expect("count query")
            .expect("count not null");
        assert_eq!(n, 5);
    }

    /// Phase C — `SELECT *` regression: the full projection path must
    /// still round-trip every column. This guards against an attno_map
    /// regression where `*` accidentally collapses to a subset.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn select_star_returns_all_columns() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-proj-star";
        let bytes = build_simple_parquet(&[7, 8, 9], &["x", "y", "z"]);
        fake.put_blob(container, "events.parquet", bytes);

        Spi::run(&install_objects_sql(
            "projstar",
            &fake,
            container,
            "events.parquet",
        ))
        .expect("install foreign objects");

        let sum: Option<i64> =
            Spi::get_one("SELECT SUM(id)::bigint FROM events_projstar").expect("sum");
        assert_eq!(sum, Some(7 + 8 + 9));
        let concat: Option<String> =
            Spi::get_one("SELECT string_agg(name, ',' ORDER BY id) FROM events_projstar")
                .expect("concat");
        assert_eq!(concat.as_deref(), Some("x,y,z"));
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn glob_matches_multiple_blobs() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-select-glob";

        for (suffix, base) in [("a", 0_i64), ("b", 4), ("c", 8)] {
            let ids: Vec<i64> = (base..base + 4).collect();
            let names: Vec<String> = ids.iter().map(|i| format!("r{i}")).collect();
            let name_refs: Vec<&str> = names.iter().map(String::as_str).collect();
            let bytes = build_simple_parquet(&ids, &name_refs);
            fake.put_blob(container, &format!("events/part-{suffix}.parquet"), bytes);
        }

        Spi::run(&install_objects_sql(
            "glob",
            &fake,
            container,
            "events/*.parquet",
        ))
        .expect("install foreign objects");

        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_glob")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 12, "glob should match all three blobs");

        let max_id = Spi::get_one::<i64>("SELECT MAX(id) FROM events_glob")
            .expect("max query")
            .expect("max not null");
        assert_eq!(max_id, 11);
    }

    // ---------------------------------------------------------------------
    // End-to-end INSERT / COPY suite (Task 17).
    //
    // The write path uploads a single block blob per `EndForeignModify` call,
    // named `{prefix}{ts}-{uuid}.parquet` when the table's `filename` option
    // contains a `*` (treated as a prefix). For round-trip checks, each test
    // creates TWO foreign tables on the same container:
    //   - a write-side table whose `filename` is a prefix like `'inserts/'` or
    //     a glob like `'inserts/*'` so each INSERT lands in a fresh blob,
    //   - a read-side table whose `filename` is the glob `'inserts/*.parquet'`
    //     so the just-written blob is picked up by the scan.
    //
    // ROLLBACK semantics (spec §7.2): Postgres DOES call
    // `EndForeignModify` on the abort path, so the FDW must check
    // `IsAbortedTransactionBlockState()` and skip the upload when aborted.
    // The boxed `ModifyState` is then dropped (freeing builders/writer) and
    // no blob is created.
    #[cfg(feature = "pg_test")]
    fn install_insert_objects_sql(
        suffix: &str,
        fake: &FakeBlobStore,
        container: &str,
        write_filename: &str,
        read_filename: &str,
    ) -> String {
        let sas = fake.sas_url(container);
        format!(
            r#"
            DROP FOREIGN TABLE IF EXISTS events_w_{suffix} CASCADE;
            DROP FOREIGN TABLE IF EXISTS events_r_{suffix} CASCADE;
            DROP USER MAPPING IF EXISTS FOR CURRENT_USER SERVER az_{suffix};
            DROP SERVER IF EXISTS az_{suffix} CASCADE;

            CREATE SERVER az_{suffix} FOREIGN DATA WRAPPER parquet_azure_fdw
              OPTIONS (account_name 'fakeaccount',
                       endpoint 'blob.core.windows.net',
                       auth_method 'sas_url');
            CREATE USER MAPPING FOR CURRENT_USER SERVER az_{suffix}
              OPTIONS (sas_url '{sas}');
            CREATE FOREIGN TABLE events_w_{suffix} (id bigint, name text)
              SERVER az_{suffix}
              OPTIONS (container '{container}', filename '{write_filename}');
            CREATE FOREIGN TABLE events_r_{suffix} (id bigint, name text)
              SERVER az_{suffix}
              OPTIONS (container '{container}', filename '{read_filename}');
            "#
        )
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn insert_then_select_round_trip() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-insert-roundtrip";

        Spi::run(&install_insert_objects_sql(
            "ins",
            &fake,
            container,
            // Trailing `*` makes pick_target_name treat `inserts/` as a prefix
            // and synthesize `inserts/{ts}-{uuid}.parquet`.
            "inserts/*",
            "inserts/*.parquet",
        ))
        .expect("install foreign objects");

        Spi::run("INSERT INTO events_w_ins VALUES (1,'alice'), (2,'bob'), (3,'carol')")
            .expect("insert");

        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_r_ins")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 3, "expected 3 rows round-tripped via Azure");

        let max_id = Spi::get_one::<i64>("SELECT MAX(id) FROM events_r_ins")
            .expect("max query")
            .expect("max not null");
        assert_eq!(max_id, 3);
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn copy_from_stdin_round_trip() {
        // NOTE: pgrx's `Spi::run` does not provide a way to feed STDIN to a
        // `COPY ... FROM STDIN` statement (the SPI client interface has no
        // hook for the CopyData sub-protocol). The brief permits substituting
        // a multi-row `INSERT ... SELECT` here; we use `INSERT ... VALUES`
        // generated by `generate_series` to drive a larger batch through the
        // same `ExecForeignInsert` callback path that COPY would.
        let fake = FakeBlobStore::start_blocking();
        let container = "test-copy-roundtrip";

        Spi::run(&install_insert_objects_sql(
            "cpy",
            &fake,
            container,
            "copies/*",
            "copies/*.parquet",
        ))
        .expect("install foreign objects");

        Spi::run(
            "INSERT INTO events_w_cpy
               SELECT g, 'row-' || g FROM generate_series(1, 25) g",
        )
        .expect("insert from select");

        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_r_cpy")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 25);

        let sum = Spi::get_one::<i64>("SELECT SUM(id)::bigint FROM events_r_cpy")
            .expect("sum query")
            .expect("sum not null");
        assert_eq!(sum, (1..=25).sum::<i64>());
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn rollback_before_end_modify_drops_buffer() {
        // Per spec §7.2: a transaction abort BEFORE `EndForeignModify`
        // commits (i.e. before the upload happens) must not produce a blob.
        // `end_foreign_modify` is in fact called on the abort path too, so
        // the implementation must check `IsAbortedTransactionBlockState()`
        // and skip the upload. We verify by enumerating the container's
        // blob list directly — `SELECT COUNT(*)` over a foreign table can't
        // distinguish "no blob present" from "an empty-rows parquet was
        // uploaded" (both yield 0 rows).
        let fake = FakeBlobStore::start_blocking();
        let container = "test-rollback-noop";

        // Pre-condition: container is empty.
        let before = fake.list_blobs(container, None);
        assert!(
            before.is_empty(),
            "container should start empty; found {before:?}"
        );

        Spi::run(&install_insert_objects_sql(
            "rb",
            &fake,
            container,
            "aborted/*",
            "aborted/*.parquet",
        ))
        .expect("install foreign objects");

        // Spi::connect inside pgrx wraps each `Spi::run` in its own
        // subtransaction, so BEGIN/INSERT/ROLLBACK as separate top-level
        // commands don't share state. Drive the whole sequence as a single
        // SQL string so it executes in one SPI connection.
        let r = Spi::run(
            "BEGIN; \
             INSERT INTO events_w_rb VALUES (99, 'never'); \
             ROLLBACK;",
        );
        // The ROLLBACK may surface as an Spi error in some pgrx versions; we
        // tolerate it. The invariant we care about is "no blob was uploaded",
        // checked next.
        let _ = r;

        // Source of truth: ask the fake directly. The container must contain
        // zero blobs — not even an empty-rows parquet (header+footer only).
        let after = fake.list_blobs(container, None);
        assert!(
            after.is_empty(),
            "rollback before EndForeignModify must not upload any blob; \
             found: {after:?}"
        );
    }

    // ---------------------------------------------------------------------
    // Error-path suite (Task 18).
    //
    // These cases assert the FDW raises a *clear* error (via `error::raise`
    // → `pgrx::error!` → `ereport!(ERROR)`) rather than panicking or
    // silently misbehaving on bad user input. We cover both the validator
    // entry point (`parquet_azure_fdw_validator`, fired at CREATE time)
    // and a runtime path (SELECT against a missing blob, which surfaces
    // an `FdwError::Azure` from the reader).
    //
    // `#[pg_test(error = "...")]` requires an EXACT match against the
    // `ereport!(ERROR)` message string — see `pgrx-tests/framework.rs`
    // (`Some(received_error_message) == expected_error`). Substring
    // matching is NOT performed, so the expected strings below reproduce
    // the full `Display` rendering of the corresponding `FdwError`
    // variant. For runtime errors raised during query execution (not at
    // CREATE time) we fall back to `Spi::run(...).unwrap_err()` and
    // assert on the `SpiError::Display` rendering with a `contains`
    // check.

    /// Bogus auth_method must be rejected at validate time with a message
    /// echoing the offending value so the user can spot the typo.
    #[pg_test(error = "invalid option: auth_method='bogus'")]
    fn invalid_auth_method_rejected() {
        Spi::run(
            r#"CREATE SERVER s_bad_auth FOREIGN DATA WRAPPER parquet_azure_fdw
                 OPTIONS (account_name 'acct', auth_method 'bogus')"#,
        )
        .unwrap();
    }

    /// `account_key` is rejected up front (azure_storage_blob 1.0 has no
    /// shared-key policy) and the error must point users at `sas_url`.
    #[pg_test(
        error = "invalid option: auth_method='account_key' is not supported by azure_storage_blob 1.0; generate a container SAS client-side and use auth_method='sas_url'"
    )]
    fn account_key_auth_remediated() {
        Spi::run(
            r#"CREATE SERVER s_acct_key FOREIGN DATA WRAPPER parquet_azure_fdw
                 OPTIONS (account_name 'acct', auth_method 'account_key')"#,
        )
        .unwrap();
    }

    /// Missing the required `auth_method` SERVER option must surface
    /// `missing required option: auth_method` rather than defaulting to
    /// something surprising.
    #[pg_test(error = "missing required option: auth_method")]
    fn missing_required_option() {
        Spi::run(
            r#"CREATE SERVER s_missing FOREIGN DATA WRAPPER parquet_azure_fdw
                 OPTIONS (account_name 'acct')"#,
        )
        .unwrap();
    }

    /// `..` path segments in a `filename` option are a traversal smell and
    /// must be rejected by the table-options parser at CREATE time.
    #[pg_test(error = "invalid option: filename must not contain '..' path segments")]
    fn glob_with_dotdot_rejected() {
        // Stand up a valid server + user mapping first; the failure must
        // come from the FOREIGN TABLE validator, not the SERVER one.
        Spi::run(
            r#"CREATE SERVER s_dotdot FOREIGN DATA WRAPPER parquet_azure_fdw
                 OPTIONS (account_name 'acct', auth_method 'sas_url');
               CREATE USER MAPPING FOR CURRENT_USER SERVER s_dotdot
                 OPTIONS (sas_url 'https://acct.blob.core.windows.net/cont?sv=x');
               CREATE FOREIGN TABLE t_dotdot (id bigint) SERVER s_dotdot
                 OPTIONS (container 'cont', filename '../etc/passwd');"#,
        )
        .unwrap();
    }

    // NOTE on a deliberately-omitted runtime error case:
    //
    // The task brief asked for a SELECT-time error (missing blob / bad
    // SAS URL) test. Both variants crash the test backend with SIGABRT
    // — the FDW *does* raise `pgrx::error!` via `error::raise` as
    // designed, but the resulting longjmp through the surrounding
    // `Spi::run` SPI subtransaction triggers a double-fault during
    // panic-to-ereport conversion in this pgrx version. The validator
    // error paths above exercise the same `error::raise` plumbing on
    // the path that *does* survive (called directly by PG, no nested
    // SPI). The runtime-error coverage gap is tracked in the Task 18
    // report (DONE_WITH_CONCERNS).

    /// End-to-end coverage for Task 10 of the qual-pushdown plan: prove the
    /// pushdown branch in `scan.rs` (the `enable_pushdown` arm) is exercised
    /// without breaking correctness. We don't assert *that* pruning fired —
    /// row-group stats are flaky to introspect — only that a SELECT with a
    /// pushable `=` predicate still returns the right rows. The multi
    /// row-group fixture (3 row-groups of 4 rows each spanning disjoint id
    /// ranges 0..3, 100..103, 200..203) gives the pruning code something
    /// non-trivial to chew on; correctness then implies soundness.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pushdown_eq_returns_correct_rows() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-pushdown-eq";
        let bytes = build_multi_rowgroup_parquet();
        fake.put_blob(container, "big.parquet", bytes);

        Spi::run(&install_objects_sql(
            "pdeq",
            &fake,
            container,
            "big.parquet",
        ))
        .expect("install foreign objects");

        // Equality on `id = 100` should hit exactly one row (in the middle
        // row-group). Exercises the pushed-eq path.
        let n_eq = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_pdeq WHERE id = 100")
            .expect("count eq query")
            .expect("count not null");
        assert_eq!(n_eq, 1, "id = 100 must match exactly one row");

        // And the value comes back correctly when projected.
        let name: Option<String> =
            Spi::get_one("SELECT name FROM events_pdeq WHERE id = 100").expect("select name");
        assert_eq!(name.as_deref(), Some("n100"));

        // Greater-than crossing a row-group boundary: id > 150 selects all
        // four ids in the 200..203 group. Exercises the pushed-gt path.
        let n_gt = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_pdeq WHERE id > 150")
            .expect("count gt query")
            .expect("count not null");
        assert_eq!(n_gt, 4, "ids 200..203 = 4 rows");
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn row_group_pruning_skips_groups() {
        // v1 LIMITATION: qual pushdown is stubbed in Task 11. The FDW does
        // NOT skip row-groups based on WHERE clauses — PostgreSQL applies the
        // filter post-scan. We only verify SELECT correctness with a WHERE
        // clause; when real pushdown lands, add an EXPLAIN check that the
        // FDW skipped row-groups 1 and 2.
        let fake = FakeBlobStore::start_blocking();
        let container = "test-select-rowgroups";
        let bytes = build_multi_rowgroup_parquet();
        fake.put_blob(container, "big.parquet", bytes);

        Spi::run(&install_objects_sql("rg", &fake, container, "big.parquet"))
            .expect("install foreign objects");

        let total = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_rg")
            .expect("count query")
            .expect("count not null");
        assert_eq!(total, 12, "3 row-groups x 4 rows = 12");

        let filtered = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_rg WHERE id > 100")
            .expect("count query")
            .expect("count not null");
        assert_eq!(filtered, 7, "ids 101..103 + 200..203 = 7 rows");
    }

    // ---------------------------------------------------------------------
    // Live Azure smoke test (Task 22).
    //
    // OPT-IN: This `#[pg_test]` runs against a REAL Azure storage container
    // when the `AZURE_TEST_SAS_URL` environment variable is set to a full
    // container SAS URL of the form
    //   `https://<account>.blob.core.windows.net/<container>?<sas-querystring>`
    // with at least `racwl` permissions (read, add, create, write, list).
    //
    // Without the env var the test is a no-op early-return so CI without
    // the secret is a pass. The SAS URL is parsed to extract the account
    // and container; the `endpoint` SERVER option is a no-op placeholder
    // for the SasUrl auth path (the full pre-signed URL carries everything
    // we need) but is still required by the SERVER options validator.
    //
    // CLEANUP: each invocation uses a unique `smoke-<uuid>/` blob prefix so
    // concurrent runs don't collide. We do NOT delete blobs at end of test
    // (the FDW has no DELETE path); the prefix is printed so a human can
    // clean up via `az storage blob delete-batch` if desired.
    fn parse_sas_url(url: &str) -> Option<(String, String, String)> {
        let u = url::Url::parse(url).ok()?;
        let host = u.host_str()?;
        let account = host.split('.').next()?.to_string();
        let path = u.path().trim_start_matches('/');
        let container = path.split('/').next()?.to_string();
        if account.is_empty() || container.is_empty() {
            return None;
        }
        Some((account, container, url.to_string()))
    }

    #[pg_test]
    fn live_smoke_write_then_read() {
        let Some((account, container, sas)) = std::env::var("AZURE_TEST_SAS_URL")
            .ok()
            .and_then(|s| parse_sas_url(&s))
        else {
            eprintln!("AZURE_TEST_SAS_URL not set; skipping live Azure smoke test");
            return;
        };

        let prefix = format!("smoke-{}", uuid::Uuid::new_v4());
        eprintln!(
            "live_smoke: account={account} container={container} prefix={prefix} \
             (blobs will be left in place; clean up manually if needed)"
        );

        let write_filename = format!("{prefix}/*");
        let read_filename = format!("{prefix}/*.parquet");

        Spi::run(&format!(
            r#"
            DROP FOREIGN TABLE IF EXISTS live_w CASCADE;
            DROP FOREIGN TABLE IF EXISTS live_r CASCADE;
            DROP USER MAPPING IF EXISTS FOR CURRENT_USER SERVER live_az;
            DROP SERVER IF EXISTS live_az CASCADE;

            CREATE SERVER live_az FOREIGN DATA WRAPPER parquet_azure_fdw
              OPTIONS (account_name '{account}',
                       endpoint 'blob.core.windows.net',
                       auth_method 'sas_url');
            CREATE USER MAPPING FOR CURRENT_USER SERVER live_az
              OPTIONS (sas_url '{sas}');
            CREATE FOREIGN TABLE live_w (id bigint, name text)
              SERVER live_az
              OPTIONS (container '{container}', filename '{write_filename}');
            CREATE FOREIGN TABLE live_r (id bigint, name text)
              SERVER live_az
              OPTIONS (container '{container}', filename '{read_filename}');
            INSERT INTO live_w VALUES (1,'alpha'),(2,'beta'),(3,'gamma');
            "#
        ))
        .expect("install + insert against live Azure");

        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM live_r WHERE id IN (1,2,3)")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 3);
    }

    // ---------------------------------------------------------------------
    // End-to-end UPDATE / DELETE suite (Task 15).
    //
    // Each test:
    //   1. Seeds a container with a `data.parquet` of `(id bigint, name text)`
    //      via the harness `put_blob` + `build_simple_parquet` path.
    //   2. Wires SERVER / USER MAPPING / FOREIGN TABLE against that single
    //      blob (no glob — UPDATE/DELETE addresses fixed blob names).
    //   3. Drives the FDW via SPI and asserts via SELECT or, where the
    //      assertion is "no Azure I/O happened", via `read_etag` against
    //      the underlying blob.
    //
    // Schema-mapping note: `build_simple_parquet` produces parquet columns
    // named `id` (Int64) and `name` (Utf8). The foreign table's column
    // names are matched by name in `pg_attrs_to_arrow_schema`, so the
    // foreign table column names must match the parquet column names.

    #[cfg(feature = "pg_test")]
    fn install_modify_objects_sql(suffix: &str, fake: &FakeBlobStore, container: &str) -> String {
        let sas = fake.sas_url(container);
        format!(
            r#"
            DROP FOREIGN TABLE IF EXISTS mod_{suffix} CASCADE;
            DROP USER MAPPING IF EXISTS FOR CURRENT_USER SERVER azm_{suffix};
            DROP SERVER IF EXISTS azm_{suffix} CASCADE;

            CREATE SERVER azm_{suffix} FOREIGN DATA WRAPPER parquet_azure_fdw
              OPTIONS (account_name 'fakeaccount',
                       endpoint 'blob.core.windows.net',
                       auth_method 'sas_url');
            CREATE USER MAPPING FOR CURRENT_USER SERVER azm_{suffix}
              OPTIONS (sas_url '{sas}');
            CREATE FOREIGN TABLE mod_{suffix} (id bigint, name text)
              SERVER azm_{suffix}
              OPTIONS (container '{container}', filename 'data.parquet');
            "#
        )
    }

    /// Seed a fresh fake container with a known two-row `data.parquet` and
    /// install the foreign-table SQL stack. Returns the fake so each test
    /// can use it for direct etag/blob inspection.
    #[cfg(feature = "pg_test")]
    fn setup_two_row_modify(suffix: &str, container: &str) -> FakeBlobStore {
        let fake = FakeBlobStore::start_blocking();
        let bytes = build_simple_parquet(&[1, 2], &["a", "b"]);
        fake.put_blob(container, "data.parquet", bytes);
        Spi::run(&install_modify_objects_sql(suffix, &fake, container))
            .expect("install foreign objects");
        fake
    }

    // HISTORICAL (T15): the COMMIT path of these tests once produced a
    // SIGABRT inside `commit_plan` because we relied on the executor's
    // `tts_tid` field, which the planner does not always populate. T15's fix
    // (`add_row_identity_var` + a resjunk `ctid` junk-attribute fetched in
    // `exec_foreign_{update,delete}`) eliminated the crash, and every
    // single-process test below now runs unignored. The one remaining
    // `#[ignore]` is `pg_update_serialization_failure`, which models a
    // *concurrent* update from a second backend — pgrx's single-process
    // test harness can't drive two backends, so we cover that path via the
    // wiremock-based `tests/update_delete.rs::etag_conflict_returns_*` cases
    // and leave the pg_test stub in place for the day we add a multi-backend
    // harness.

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_update_basic() {
        let container = "pg-upd-basic";
        let _fake = setup_two_row_modify("upd_basic", container);

        Spi::run("UPDATE mod_upd_basic SET name = 'new' WHERE id = 1").unwrap();
        let v: Option<String> =
            Spi::get_one("SELECT name FROM mod_upd_basic WHERE id = 1").unwrap();
        assert_eq!(v.as_deref(), Some("new"));

        // Untouched row still present with original value.
        let v2: Option<String> =
            Spi::get_one("SELECT name FROM mod_upd_basic WHERE id = 2").unwrap();
        assert_eq!(v2.as_deref(), Some("b"));
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_delete_basic() {
        let container = "pg-del-basic";
        let _fake = setup_two_row_modify("del_basic", container);

        Spi::run("DELETE FROM mod_del_basic WHERE id = 1").unwrap();
        let n: Option<i64> = Spi::get_one("SELECT count(*)::bigint FROM mod_del_basic").unwrap();
        assert_eq!(n, Some(1));

        // The surviving row is the one we didn't target.
        let surviving: Option<i64> = Spi::get_one("SELECT id FROM mod_del_basic").unwrap();
        assert_eq!(surviving, Some(2));
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_update_returning_echoes_new_value() {
        let container = "pg-upd-ret";
        let _fake = setup_two_row_modify("upd_ret", container);

        let v: Option<String> =
            Spi::get_one("UPDATE mod_upd_ret SET name = 'r' WHERE id = 2 RETURNING name").unwrap();
        assert_eq!(v.as_deref(), Some("r"));
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_delete_where_false_is_noop() {
        // DELETE matching zero rows must produce ZERO Azure I/O — the
        // accumulator stays empty so `commit_plan` never enters its
        // per-blob GET/PUT loop, and the blob's etag is unchanged.
        let container = "pg-del-false";
        let fake = setup_two_row_modify("del_false", container);

        let pre_etag = fake
            .read_etag(container, "data.parquet")
            .expect("blob exists pre");

        Spi::run("DELETE FROM mod_del_false WHERE id = 99").unwrap();

        let post_etag = fake
            .read_etag(container, "data.parquet")
            .expect("blob exists post");
        assert_eq!(
            pre_etag, post_etag,
            "no rows matched — no Azure I/O expected"
        );

        // Row count unchanged.
        let n: Option<i64> = Spi::get_one("SELECT count(*)::bigint FROM mod_del_false").unwrap();
        assert_eq!(n, Some(2));
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_rollback_discards_pending_edits() {
        // BEGIN; UPDATE; ROLLBACK; — `end_foreign_modify` sees
        // `IsAbortedTransactionBlockState()` and must skip `commit_plan`,
        // leaving the blob unchanged.
        //
        // As in the INSERT-side rollback test (`rollback_before_end_modify_drops_buffer`),
        // BEGIN/UPDATE/ROLLBACK must be executed as a single SPI batch — issuing
        // them as separate `Spi::run` calls wraps each in its own subtransaction
        // and the BEGIN/ROLLBACK pair becomes a no-op.
        let container = "pg-rb";
        let fake = setup_two_row_modify("rb", container);

        let pre_etag = fake
            .read_etag(container, "data.parquet")
            .expect("blob exists pre");

        let r = Spi::run(
            "BEGIN; \
             UPDATE mod_rb SET name = 'z' WHERE id = 1; \
             ROLLBACK;",
        );
        let _ = r; // ROLLBACK may surface as an Spi error in some pgrx versions.

        let post_etag = fake
            .read_etag(container, "data.parquet")
            .expect("blob exists post");
        assert_eq!(
            pre_etag, post_etag,
            "ROLLBACK must not commit edits to the blob"
        );

        // And a fresh SELECT sees the original row, not the rolled-back edit.
        let v: Option<String> = Spi::get_one("SELECT name FROM mod_rb WHERE id = 1").unwrap();
        assert_eq!(v.as_deref(), Some("a"));
    }

    /// Concurrent serialization-failure — end-to-end through the FDW's
    /// `commit_plan`.
    ///
    /// The SQL harness (`pgrx test`) is single-process / single-session,
    /// so we cannot drive a concurrent SQL writer between `begin_foreign_scan`
    /// and `end_foreign_modify` of the *same* UPDATE statement. Instead, the
    /// full wiring is covered by the integration test
    /// `tests/update_delete.rs::scan_handoff_to_commit_plan_lost_update_guard`,
    /// which:
    ///
    /// 1. publishes a real scan-time handoff via `scan_handoff::publish`,
    /// 2. drives `commit_plan` directly against the wiremock fake,
    /// 3. overwrites the blob out-of-band to bump its ETag,
    /// 4. asserts the resulting error is `FdwError::ConcurrentUpdate`
    ///    (which `error::raise` maps to SQLSTATE 40001).
    ///
    /// The lower-level Azure-API mapping (412 → `ConcurrentUpdate`) is in
    /// turn covered by `concurrent_etag_conflict_returns_serialization_failure`.
    /// Together those two tests fence the load-bearing invariant from both
    /// ends: the wire mapping AND the full plan→commit plumbing.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    #[ignore]
    fn pg_update_serialization_failure() {
        // Intentionally empty — see doc-comment for the rationale and for
        // the integration-test coverage that fences the same invariant.
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_update_then_select() {
        // Same session: UPDATE then SELECT. The FDW must NOT cache stale
        // blob bytes across statements — the second statement issues a
        // fresh GET against the fake and sees the new etag/body.
        let container = "pg-upd-then-sel";
        let _fake = setup_two_row_modify("upd_then_sel", container);

        Spi::run("UPDATE mod_upd_then_sel SET name = 'fresh' WHERE id = 1").unwrap();
        let v: Option<String> =
            Spi::get_one("SELECT name FROM mod_upd_then_sel WHERE id = 1").unwrap();
        assert_eq!(v.as_deref(), Some("fresh"));

        // And a follow-up UPDATE on the other row works on top of the
        // first one's committed state.
        Spi::run("UPDATE mod_upd_then_sel SET name = 'also' WHERE id = 2").unwrap();
        let v2: Option<String> =
            Spi::get_one("SELECT name FROM mod_upd_then_sel WHERE id = 2").unwrap();
        assert_eq!(v2.as_deref(), Some("also"));
        // The earlier edit must persist.
        let v1: Option<String> =
            Spi::get_one("SELECT name FROM mod_upd_then_sel WHERE id = 1").unwrap();
        assert_eq!(v1.as_deref(), Some("fresh"));
    }
}

#[cfg(test)]
pub mod pg_test {
    pub fn setup(_options: Vec<&str>) {}
    pub fn postgresql_conf_options() -> Vec<&'static str> {
        vec![]
    }
}
