#![deny(unsafe_code)]
#![allow(clippy::result_large_err)]
//! Crate root. `unsafe` is denied globally; `fdw::scan` and `fdw::modify`
//! carve themselves out via `#[allow(unsafe_code)]` (they are the FFI
//! boundary to Postgres' executor and additionally enable
//! `deny(unsafe_op_in_unsafe_fn)` so each unsafe op is still individually
//! opted into). `fdw::build_routine` also opts in for the single
//! `alloc_node` call. Every other module remains free of `unsafe`.

pub mod azure;
pub mod convert;
pub mod error;
pub mod fdw;
pub mod parquet_io;
pub mod redact;
pub mod runtime;

#[cfg(feature = "pg_test")]
pub mod test_harness;

use pgrx::guc::{GucContext, GucFlags, GucRegistry, GucSetting};
use pgrx::prelude::*;

pgrx::pg_module_magic!();

/// When off, a foreign table declared with `sorted` / `files_in_order` still
/// returns correct rows, but via the sequential per-blob scan (no K-way
/// merge; PG adds a Sort if the query needs ordering). Default on.
pub(crate) static ENABLE_MULTIFILE: GucSetting<bool> = GucSetting::<bool>::new(true);

/// PG backend init hook. Runs once per backend (after `pg_module_magic!`
/// registers the library). We use it to register our `XactCallback` for
/// staging-blob cleanup on transaction abort — see
/// `fdw::modify::coordinator::install_xact_callback_once`.
#[pg_guard]
extern "C-unwind" fn _PG_init() {
    crate::fdw::modify::coordinator::install_xact_callback_once();

    GucRegistry::define_bool_guc(
        c"parquet_fdw.enable_multifile",
        c"Enable the multi-file K-way sorted-merge reader.",
        c"When off, tables declared with `sorted`/`files_in_order` return \
          correct rows via the sequential per-blob scan instead of the merge.",
        &ENABLE_MULTIFILE,
        GucContext::Userset,
        GucFlags::default(),
    );
}

/// FDW handler — returns an `FdwRoutine` populated with our callbacks.
/// pgrx maps the `PgBox<FdwRoutine>` return into PG's `fdw_handler` type, so
/// no custom `sql=` override is needed: the generated `CREATE FUNCTION` will
/// already say `RETURNS fdw_handler`.
#[pg_extern]
fn parquet_azure_fdw_handler() -> PgBox<pg_sys::FdwRoutine, pgrx::AllocatedByRust> {
    fdw::build_routine()
}

/// FDW validator — invoked by PG for every `CREATE/ALTER SERVER`,
/// `USER MAPPING`, or `FOREIGN TABLE` against this wrapper. We hand the raw
/// `text[]` straight to [`fdw::options::validate`] which dispatches by
/// catalog OID to the matching parser; any [`error::FdwError`] is reraised
/// as a PG `ERROR`.
#[pg_extern]
fn parquet_azure_fdw_validator(options: Vec<Option<String>>, catalog: pg_sys::Oid) {
    if let Err(e) = fdw::options::validate(options, catalog) {
        crate::error::raise(e);
    }
}

// Create the FDW itself. The handler/validator CREATE FUNCTION lines are
// auto-generated by pgrx from the `#[pg_extern]` attributes above, so we
// only need to wire them into a FOREIGN DATA WRAPPER.
extension_sql!(
    r#"
    CREATE FOREIGN DATA WRAPPER parquet_azure_fdw
        HANDLER parquet_azure_fdw_handler
        VALIDATOR parquet_azure_fdw_validator;
    "#,
    name = "parquet_azure_fdw_bootstrap",
    requires = [parquet_azure_fdw_handler, parquet_azure_fdw_validator],
);

// ---------------------------------------------------------------------------
// SP-2 Task 5: SQL helpers wrapping IMPORT FOREIGN SCHEMA.
//
// `import_parquet_azure` is a thin SPI wrapper that builds an
// `IMPORT FOREIGN SCHEMA … FROM SERVER … INTO …` statement and runs it; the
// FDW's `ImportForeignSchema` callback (SP-2 Task 4) handles grouping +
// schema inference + DDL emission.
//
// `import_parquet_azure_explicit` registers a single foreign table over an
// explicit `<container>/<blob>` source. It resolves the server OID via the
// catalog, then calls `client_for_server` → `infer_columns` →
// `build_create_table_ddl` and runs the DDL via SPI. v1 supports exactly one
// source per call; multi-source is rejected with `feature_not_supported`.
// ---------------------------------------------------------------------------

/// SQL-callable wrapper for IMPORT FOREIGN SCHEMA semantics.
///
/// - `server_name`: the FOREIGN SERVER to query.
/// - `container`: the Azure container name (passed as the FDW's `container` OPTION).
/// - `remote_prefix`: blob-name prefix to list under (passed as PG's
///   `IMPORT FOREIGN SCHEMA <remote_schema>` identifier — the FDW callback
///   treats this as the LIST prefix within the container; an empty prefix
///   would mean "list everything" but PG requires a non-empty identifier
///   here, so we reject empty `remote_prefix` explicitly).
/// - `target_schema`: the local PG schema to import the foreign tables into.
///
/// Delegates to the FDW's own `ImportForeignSchema` callback via SPI.
#[pg_extern(volatile)]
fn import_parquet_azure(
    server_name: &str,
    container: &str,
    remote_prefix: &str,
    target_schema: &str,
) -> Result<(), pgrx::pg_sys::panic::ErrorReport> {
    if remote_prefix.is_empty() {
        return Err(make_err(
            "remote_prefix must be non-empty (PG IMPORT FOREIGN SCHEMA requires a name)".into(),
        ));
    }
    let sql = format!(
        "IMPORT FOREIGN SCHEMA {prefix} FROM SERVER {srv} INTO {schema} \
         OPTIONS (container {cont})",
        prefix = pgrx::spi::quote_identifier(remote_prefix),
        srv = pgrx::spi::quote_identifier(server_name),
        schema = pgrx::spi::quote_identifier(target_schema),
        cont = pgrx::spi::quote_literal(container),
    );
    pgrx::Spi::run(&sql).map_err(map_spi_err)?;
    Ok(())
}

/// SQL-callable helper that registers exactly one foreign table over an
/// explicit blob source of the form `<container>/<blob>`. Multi-source is
/// not yet supported in v1 and is rejected up front.
#[pg_extern(volatile)]
fn import_parquet_azure_explicit(
    server_name: &str,
    target_schema: &str,
    table_name: &str,
    sources: Vec<String>,
) -> Result<(), pgrx::pg_sys::panic::ErrorReport> {
    if sources.len() != 1 {
        return Err(pgrx::pg_sys::panic::ErrorReport::new(
            pgrx::PgSqlErrorCode::ERRCODE_FEATURE_NOT_SUPPORTED,
            "import_parquet_azure_explicit currently supports exactly one source per call",
            "",
        ));
    }
    let source = &sources[0];

    // Resolve server OID by name via the catalog.
    let oid_sql = "SELECT oid FROM pg_foreign_server WHERE srvname = $1";
    let server_oid: pgrx::pg_sys::Oid = pgrx::Spi::get_one_with_args(
        oid_sql,
        &[pgrx::datum::DatumWithOid::from(server_name.to_string())],
    )
    .map_err(map_spi_err)?
    .ok_or_else(|| make_err(format!("server '{server_name}' not found")))?;

    // v1: container is the first path segment, blob name is the rest.
    let (container, blob_name) = match source.split_once('/') {
        Some((c, b)) if !c.is_empty() && !b.is_empty() => (c.to_string(), b.to_string()),
        _ => return Err(make_err("source must be '<container>/<blob>'".into())),
    };

    crate::fdw::options::validate_container_name(&container)
        .map_err(|e| make_err(format!("{e}")))?;
    crate::fdw::options::validate_blob_pattern(&blob_name, "source blob name")
        .map_err(|e| make_err(format!("{e}")))?;

    let client = crate::fdw::import_schema::client_for_server(server_oid, &container)
        .map_err(|e| make_err(format!("{e}")))?;
    let cols = crate::fdw::import_schema::infer_columns(&client, &blob_name)
        .map_err(|e| make_err(format!("{e}")))?;
    let ddl = crate::fdw::import_schema::build_create_table_ddl(
        target_schema,
        table_name,
        server_name,
        &container,
        &blob_name,
        &cols,
    );
    pgrx::Spi::run(&ddl).map_err(map_spi_err)?;
    Ok(())
}

fn make_err(msg: String) -> pgrx::pg_sys::panic::ErrorReport {
    pgrx::pg_sys::panic::ErrorReport::new(pgrx::PgSqlErrorCode::ERRCODE_FDW_ERROR, msg, "")
}

fn map_spi_err<E: std::fmt::Display>(e: E) -> pgrx::pg_sys::panic::ErrorReport {
    make_err(format!("SPI: {e}"))
}

#[cfg(any(test, feature = "pg_test"))]
#[pgrx::pg_schema]
mod tests {
    use pgrx::prelude::*;

    #[pg_test]
    fn smoke() {
        assert_eq!(Spi::get_one::<i32>("SELECT 1").unwrap(), Some(1));
    }

    /// SP-2 Task 5: the explicit helper must reject multi-source calls
    /// with `feature_not_supported`. Single-source happy-path requires a
    /// real Azure backend and is deferred to a future smoke test.
    #[pg_test(
        error = "import_parquet_azure_explicit currently supports exactly one source per call"
    )]
    fn import_parquet_azure_explicit_rejects_multi_source() {
        Spi::run(
            "SELECT import_parquet_azure_explicit('srv', 'public', 'tab', \
             ARRAY['c/a.parquet', 'c/b.parquet']);",
        )
        .unwrap();
    }

    /// Verify the extension loads cleanly and that the FDW handler +
    /// validator are usable for a real `CREATE SERVER` (without touching
    /// Azure — the validator only sanity-checks options).
    #[pg_test]
    fn extension_loads() {
        Spi::run(
            r#"CREATE SERVER s_load FOREIGN DATA WRAPPER parquet_azure_fdw
                 OPTIONS (account_name 'acct', auth_method 'managed_identity')"#,
        )
        .unwrap();
    }

    // ---------------------------------------------------------------------
    // End-to-end SELECT suite (Task 16).
    //
    // Each `#[pg_test]` here exercises the full FDW path: an in-memory
    // wiremock-backed `FakeBlobStore` holds parquet fixtures we author
    // in-process via [`ParquetBatchWriter`]; PostgreSQL talks to the FDW
    // via `CREATE FOREIGN TABLE`, the FDW resolves a SAS URL against the
    // fake, fetches the parquet bytes, and feeds row batches up through
    // `IterateForeignScan`.
    //
    // Auth note: v1 only supports `auth_method = 'sas_url'`. The fake
    // ignores the query string of the SAS URL — any URL pointing at the
    // mock server is accepted.
    //
    // Pushdown caveat: Task 11 left qual-pushdown stubbed (no row-group
    // pruning), so the `row_group_pruning_skips_groups` case only asserts
    // PG-level WHERE correctness. Once T11 grows real predicate pushdown,
    // an EXPLAIN check that the FDW reports fewer `rows_processed` becomes
    // meaningful.
    #[cfg(feature = "pg_test")]
    use crate::test_harness::{build_multi_rowgroup_parquet, build_simple_parquet, FakeBlobStore};

    /// Boilerplate SQL that wires Server, UserMapping, and ForeignTable for
    /// `container` against a single blob (or glob pattern) `filename`. The
    /// `endpoint` SERVER option is a placeholder for the SasUrl auth path —
    /// the full pre-signed URL on the user mapping carries everything the
    /// SDK needs to reach the fake.
    #[cfg(feature = "pg_test")]
    fn install_objects_sql(
        suffix: &str,
        fake: &FakeBlobStore,
        container: &str,
        filename: &str,
    ) -> String {
        let sas = fake.sas_url(container);
        format!(
            r#"
            DROP FOREIGN TABLE IF EXISTS events_{suffix} CASCADE;
            DROP USER MAPPING IF EXISTS FOR CURRENT_USER SERVER az_{suffix};
            DROP SERVER IF EXISTS az_{suffix} CASCADE;

            CREATE SERVER az_{suffix} FOREIGN DATA WRAPPER parquet_azure_fdw
              OPTIONS (account_name 'fakeaccount',
                       endpoint 'blob.core.windows.net',
                       auth_method 'sas_url');
            CREATE USER MAPPING FOR CURRENT_USER SERVER az_{suffix}
              OPTIONS (sas_url '{sas}');
            CREATE FOREIGN TABLE events_{suffix} (id bigint, name text)
              SERVER az_{suffix}
              OPTIONS (container '{container}', filename '{filename}');
            "#
        )
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn select_single_blob() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-select-single";
        let bytes = build_simple_parquet(&[1, 2, 3, 4], &["a", "b", "c", "d"]);
        fake.put_blob(container, "events.parquet", bytes);

        Spi::run(&install_objects_sql(
            "single",
            &fake,
            container,
            "events.parquet",
        ))
        .expect("install foreign objects");

        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_single")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 4, "expected 4 rows from single blob");

        let max_id = Spi::get_one::<i64>("SELECT MAX(id) FROM events_single")
            .expect("max query")
            .expect("max not null");
        assert_eq!(max_id, 4);
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn projection_only_selects_one_column() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-select-proj";
        let bytes = build_simple_parquet(&[10, 20, 30, 40], &["w", "x", "y", "z"]);
        fake.put_blob(container, "events.parquet", bytes);

        Spi::run(&install_objects_sql(
            "proj",
            &fake,
            container,
            "events.parquet",
        ))
        .expect("install foreign objects");

        // v1 pushdown stub: projection list is forwarded to the parquet
        // reader via `tts_values`; we don't assert on EXPLAIN output and
        // only check correctness.
        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM (SELECT id FROM events_proj) s")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 4);

        let sum_ids = Spi::get_one::<i64>("SELECT SUM(id)::bigint FROM events_proj")
            .expect("sum query")
            .expect("sum not null");
        assert_eq!(sum_ids, 100);
    }

    /// Phase C — explicit column-projection coverage. `SELECT name FROM t`
    /// should fetch the `name` column from parquet (not all of them) AND
    /// the result should still be correct row-for-row. The previous
    /// `projection_only_selects_one_column` test only asserted that the
    /// scan completes; this one verifies the projected values themselves
    /// match the source so we'd notice if the attno_map shifted (e.g. a
    /// regression that fills the wrong slot position).
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn select_only_name_column_returns_correct_values() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-proj-name";
        let bytes = build_simple_parquet(&[10, 20, 30], &["alpha", "beta", "gamma"]);
        fake.put_blob(container, "events.parquet", bytes);

        Spi::run(&install_objects_sql(
            "projname",
            &fake,
            container,
            "events.parquet",
        ))
        .expect("install foreign objects");

        // Only the `name` column is in reltarget → projection = [name].
        // Iterate must put `name` at relation attnum 2 (slot index 1),
        // and `id` at slot index 0 must remain NULL (PG won't read it).
        let names: Vec<Option<String>> = (1..=3)
            .map(|i| {
                Spi::get_one::<String>(&format!(
                    "SELECT name FROM events_projname ORDER BY name LIMIT 1 OFFSET {}",
                    i - 1
                ))
                .expect("select name")
            })
            .collect();
        let unwrapped: Vec<String> = names.into_iter().map(|o| o.unwrap()).collect();
        assert_eq!(unwrapped, vec!["alpha", "beta", "gamma"]);
    }

    /// Phase C — count(*) edge case. `SELECT count(*) FROM t` references
    /// zero Var columns; `get_foreign_plan` must fall back to projecting
    /// column 0 so the parquet reader has something to iterate. Asserts
    /// the count is correct against the seeded row count.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn select_count_star_works_with_zero_column_projection() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-proj-count";
        let bytes = build_simple_parquet(&[1, 2, 3, 4, 5], &["a", "b", "c", "d", "e"]);
        fake.put_blob(container, "events.parquet", bytes);

        Spi::run(&install_objects_sql(
            "projcount",
            &fake,
            container,
            "events.parquet",
        ))
        .expect("install foreign objects");

        let n = Spi::get_one::<i64>("SELECT count(*)::bigint FROM events_projcount")
            .expect("count query")
            .expect("count not null");
        assert_eq!(n, 5);
    }

    /// Phase C — `SELECT *` regression: the full projection path must
    /// still round-trip every column. This guards against an attno_map
    /// regression where `*` accidentally collapses to a subset.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn select_star_returns_all_columns() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-proj-star";
        let bytes = build_simple_parquet(&[7, 8, 9], &["x", "y", "z"]);
        fake.put_blob(container, "events.parquet", bytes);

        Spi::run(&install_objects_sql(
            "projstar",
            &fake,
            container,
            "events.parquet",
        ))
        .expect("install foreign objects");

        let sum: Option<i64> =
            Spi::get_one("SELECT SUM(id)::bigint FROM events_projstar").expect("sum");
        assert_eq!(sum, Some(7 + 8 + 9));
        let concat: Option<String> =
            Spi::get_one("SELECT string_agg(name, ',' ORDER BY id) FROM events_projstar")
                .expect("concat");
        assert_eq!(concat.as_deref(), Some("x,y,z"));
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn glob_matches_multiple_blobs() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-select-glob";

        for (suffix, base) in [("a", 0_i64), ("b", 4), ("c", 8)] {
            let ids: Vec<i64> = (base..base + 4).collect();
            let names: Vec<String> = ids.iter().map(|i| format!("r{i}")).collect();
            let name_refs: Vec<&str> = names.iter().map(String::as_str).collect();
            let bytes = build_simple_parquet(&ids, &name_refs);
            fake.put_blob(container, &format!("events/part-{suffix}.parquet"), bytes);
        }

        Spi::run(&install_objects_sql(
            "glob",
            &fake,
            container,
            "events/*.parquet",
        ))
        .expect("install foreign objects");

        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_glob")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 12, "glob should match all three blobs");

        let max_id = Spi::get_one::<i64>("SELECT MAX(id) FROM events_glob")
            .expect("max query")
            .expect("max not null");
        assert_eq!(max_id, 11);
    }

    // ---------------------------------------------------------------------
    // End-to-end INSERT / COPY suite (Task 17).
    //
    // The write path uploads a single block blob per `EndForeignModify` call,
    // named `{prefix}{ts}-{uuid}.parquet` when the table's `filename` option
    // contains a `*` (treated as a prefix). For round-trip checks, each test
    // creates TWO foreign tables on the same container:
    //   - a write-side table whose `filename` is a prefix like `'inserts/'` or
    //     a glob like `'inserts/*'` so each INSERT lands in a fresh blob,
    //   - a read-side table whose `filename` is the glob `'inserts/*.parquet'`
    //     so the just-written blob is picked up by the scan.
    //
    // ROLLBACK semantics (spec §7.2): Postgres DOES call
    // `EndForeignModify` on the abort path, so the FDW must check
    // `IsAbortedTransactionBlockState()` and skip the upload when aborted.
    // The boxed `ModifyState` is then dropped (freeing builders/writer) and
    // no blob is created.
    #[cfg(feature = "pg_test")]
    fn install_insert_objects_sql(
        suffix: &str,
        fake: &FakeBlobStore,
        container: &str,
        write_filename: &str,
        read_filename: &str,
    ) -> String {
        let sas = fake.sas_url(container);
        format!(
            r#"
            DROP FOREIGN TABLE IF EXISTS events_w_{suffix} CASCADE;
            DROP FOREIGN TABLE IF EXISTS events_r_{suffix} CASCADE;
            DROP USER MAPPING IF EXISTS FOR CURRENT_USER SERVER az_{suffix};
            DROP SERVER IF EXISTS az_{suffix} CASCADE;

            CREATE SERVER az_{suffix} FOREIGN DATA WRAPPER parquet_azure_fdw
              OPTIONS (account_name 'fakeaccount',
                       endpoint 'blob.core.windows.net',
                       auth_method 'sas_url');
            CREATE USER MAPPING FOR CURRENT_USER SERVER az_{suffix}
              OPTIONS (sas_url '{sas}');
            CREATE FOREIGN TABLE events_w_{suffix} (id bigint, name text)
              SERVER az_{suffix}
              OPTIONS (container '{container}', filename '{write_filename}');
            CREATE FOREIGN TABLE events_r_{suffix} (id bigint, name text)
              SERVER az_{suffix}
              OPTIONS (container '{container}', filename '{read_filename}');
            "#
        )
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn insert_then_select_round_trip() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-insert-roundtrip";

        Spi::run(&install_insert_objects_sql(
            "ins",
            &fake,
            container,
            // Trailing `*` makes pick_target_name treat `inserts/` as a prefix
            // and synthesize `inserts/{ts}-{uuid}.parquet`.
            "inserts/*",
            "inserts/*.parquet",
        ))
        .expect("install foreign objects");

        Spi::run("INSERT INTO events_w_ins VALUES (1,'alice'), (2,'bob'), (3,'carol')")
            .expect("insert");

        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_r_ins")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 3, "expected 3 rows round-tripped via Azure");

        let max_id = Spi::get_one::<i64>("SELECT MAX(id) FROM events_r_ins")
            .expect("max query")
            .expect("max not null");
        assert_eq!(max_id, 3);
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn copy_from_stdin_round_trip() {
        // NOTE: pgrx's `Spi::run` does not provide a way to feed STDIN to a
        // `COPY ... FROM STDIN` statement (the SPI client interface has no
        // hook for the CopyData sub-protocol). The brief permits substituting
        // a multi-row `INSERT ... SELECT` here; we use `INSERT ... VALUES`
        // generated by `generate_series` to drive a larger batch through the
        // same `ExecForeignInsert` callback path that COPY would.
        let fake = FakeBlobStore::start_blocking();
        let container = "test-copy-roundtrip";

        Spi::run(&install_insert_objects_sql(
            "cpy",
            &fake,
            container,
            "copies/*",
            "copies/*.parquet",
        ))
        .expect("install foreign objects");

        Spi::run(
            "INSERT INTO events_w_cpy
               SELECT g, 'row-' || g FROM generate_series(1, 25) g",
        )
        .expect("insert from select");

        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_r_cpy")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 25);

        let sum = Spi::get_one::<i64>("SELECT SUM(id)::bigint FROM events_r_cpy")
            .expect("sum query")
            .expect("sum not null");
        assert_eq!(sum, (1..=25).sum::<i64>());
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn rollback_before_end_modify_drops_buffer() {
        // Per spec §7.2: a transaction abort BEFORE `EndForeignModify`
        // commits (i.e. before the upload happens) must not produce a blob.
        // `end_foreign_modify` is in fact called on the abort path too, so
        // the implementation must check `IsAbortedTransactionBlockState()`
        // and skip the upload. We verify by enumerating the container's
        // blob list directly — `SELECT COUNT(*)` over a foreign table can't
        // distinguish "no blob present" from "an empty-rows parquet was
        // uploaded" (both yield 0 rows).
        let fake = FakeBlobStore::start_blocking();
        let container = "test-rollback-noop";

        // Pre-condition: container is empty.
        let before = fake.list_blobs(container, None);
        assert!(
            before.is_empty(),
            "container should start empty; found {before:?}"
        );

        Spi::run(&install_insert_objects_sql(
            "rb",
            &fake,
            container,
            "aborted/*",
            "aborted/*.parquet",
        ))
        .expect("install foreign objects");

        // Spi::connect inside pgrx wraps each `Spi::run` in its own
        // subtransaction, so BEGIN/INSERT/ROLLBACK as separate top-level
        // commands don't share state. Drive the whole sequence as a single
        // SQL string so it executes in one SPI connection.
        let r = Spi::run(
            "BEGIN; \
             INSERT INTO events_w_rb VALUES (99, 'never'); \
             ROLLBACK;",
        );
        // The ROLLBACK may surface as an Spi error in some pgrx versions; we
        // tolerate it. The invariant we care about is "no blob was uploaded",
        // checked next.
        let _ = r;

        // Source of truth: ask the fake directly. The container must contain
        // zero blobs — not even an empty-rows parquet (header+footer only).
        let after = fake.list_blobs(container, None);
        assert!(
            after.is_empty(),
            "rollback before EndForeignModify must not upload any blob; \
             found: {after:?}"
        );
    }

    // ---------------------------------------------------------------------
    // Error-path suite (Task 18).
    //
    // These cases assert the FDW raises a *clear* error (via `error::raise`
    // → `pgrx::error!` → `ereport!(ERROR)`) rather than panicking or
    // silently misbehaving on bad user input. We cover both the validator
    // entry point (`parquet_azure_fdw_validator`, fired at CREATE time)
    // and a runtime path (SELECT against a missing blob, which surfaces
    // an `FdwError::Azure` from the reader).
    //
    // `#[pg_test(error = "...")]` requires an EXACT match against the
    // `ereport!(ERROR)` message string — see `pgrx-tests/framework.rs`
    // (`Some(received_error_message) == expected_error`). Substring
    // matching is NOT performed, so the expected strings below reproduce
    // the full `Display` rendering of the corresponding `FdwError`
    // variant. For runtime errors raised during query execution (not at
    // CREATE time) we fall back to `Spi::run(...).unwrap_err()` and
    // assert on the `SpiError::Display` rendering with a `contains`
    // check.

    /// Bogus auth_method must be rejected at validate time with a message
    /// echoing the offending value so the user can spot the typo.
    #[pg_test(error = "invalid option: auth_method='bogus'")]
    fn invalid_auth_method_rejected() {
        Spi::run(
            r#"CREATE SERVER s_bad_auth FOREIGN DATA WRAPPER parquet_azure_fdw
                 OPTIONS (account_name 'acct', auth_method 'bogus')"#,
        )
        .unwrap();
    }

    /// `account_key` is rejected up front (azure_storage_blob 1.0 has no
    /// shared-key policy) and the error must point users at `sas_url`.
    #[pg_test(
        error = "invalid option: auth_method='account_key' is not supported by azure_storage_blob 1.0; generate a container SAS client-side and use auth_method='sas_url'"
    )]
    fn account_key_auth_remediated() {
        Spi::run(
            r#"CREATE SERVER s_acct_key FOREIGN DATA WRAPPER parquet_azure_fdw
                 OPTIONS (account_name 'acct', auth_method 'account_key')"#,
        )
        .unwrap();
    }

    /// Missing the required `auth_method` SERVER option must surface
    /// `missing required option: auth_method` rather than defaulting to
    /// something surprising.
    #[pg_test(error = "missing required option: auth_method")]
    fn missing_required_option() {
        Spi::run(
            r#"CREATE SERVER s_missing FOREIGN DATA WRAPPER parquet_azure_fdw
                 OPTIONS (account_name 'acct')"#,
        )
        .unwrap();
    }

    /// `..` path segments in a `filename` option are a traversal smell and
    /// must be rejected by the table-options parser at CREATE time.
    #[pg_test(error = "invalid option: filename must not contain '..' path segments")]
    fn glob_with_dotdot_rejected() {
        // Stand up a valid server + user mapping first; the failure must
        // come from the FOREIGN TABLE validator, not the SERVER one.
        Spi::run(
            r#"CREATE SERVER s_dotdot FOREIGN DATA WRAPPER parquet_azure_fdw
                 OPTIONS (account_name 'acct', auth_method 'sas_url');
               CREATE USER MAPPING FOR CURRENT_USER SERVER s_dotdot
                 OPTIONS (sas_url 'https://acct.blob.core.windows.net/cont?sv=x');
               CREATE FOREIGN TABLE t_dotdot (id bigint) SERVER s_dotdot
                 OPTIONS (container 'cont', filename '../etc/passwd');"#,
        )
        .unwrap();
    }

    // NOTE on a deliberately-omitted runtime error case:
    //
    // The task brief asked for a SELECT-time error (missing blob / bad
    // SAS URL) test. Both variants crash the test backend with SIGABRT
    // — the FDW *does* raise `pgrx::error!` via `error::raise` as
    // designed, but the resulting longjmp through the surrounding
    // `Spi::run` SPI subtransaction triggers a double-fault during
    // panic-to-ereport conversion in this pgrx version. The validator
    // error paths above exercise the same `error::raise` plumbing on
    // the path that *does* survive (called directly by PG, no nested
    // SPI). The runtime-error coverage gap is tracked in the Task 18
    // report (DONE_WITH_CONCERNS).

    /// End-to-end coverage for Task 10 of the qual-pushdown plan: prove the
    /// pushdown branch in `scan.rs` (the `enable_pushdown` arm) is exercised
    /// without breaking correctness. We don't assert *that* pruning fired —
    /// row-group stats are flaky to introspect — only that a SELECT with a
    /// pushable `=` predicate still returns the right rows. The multi
    /// row-group fixture (3 row-groups of 4 rows each spanning disjoint id
    /// ranges 0..3, 100..103, 200..203) gives the pruning code something
    /// non-trivial to chew on; correctness then implies soundness.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pushdown_eq_returns_correct_rows() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-pushdown-eq";
        let bytes = build_multi_rowgroup_parquet();
        fake.put_blob(container, "big.parquet", bytes);

        Spi::run(&install_objects_sql(
            "pdeq",
            &fake,
            container,
            "big.parquet",
        ))
        .expect("install foreign objects");

        // Equality on `id = 100` should hit exactly one row (in the middle
        // row-group). Exercises the pushed-eq path.
        let n_eq = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_pdeq WHERE id = 100")
            .expect("count eq query")
            .expect("count not null");
        assert_eq!(n_eq, 1, "id = 100 must match exactly one row");

        // And the value comes back correctly when projected.
        let name: Option<String> =
            Spi::get_one("SELECT name FROM events_pdeq WHERE id = 100").expect("select name");
        assert_eq!(name.as_deref(), Some("n100"));

        // Greater-than crossing a row-group boundary: id > 150 selects all
        // four ids in the 200..203 group. Exercises the pushed-gt path.
        let n_gt = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_pdeq WHERE id > 150")
            .expect("count gt query")
            .expect("count not null");
        assert_eq!(n_gt, 4, "ids 200..203 = 4 rows");
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn row_group_pruning_skips_groups() {
        // v1 LIMITATION: qual pushdown is stubbed in Task 11. The FDW does
        // NOT skip row-groups based on WHERE clauses — PostgreSQL applies the
        // filter post-scan. We only verify SELECT correctness with a WHERE
        // clause; when real pushdown lands, add an EXPLAIN check that the
        // FDW skipped row-groups 1 and 2.
        let fake = FakeBlobStore::start_blocking();
        let container = "test-select-rowgroups";
        let bytes = build_multi_rowgroup_parquet();
        fake.put_blob(container, "big.parquet", bytes);

        Spi::run(&install_objects_sql("rg", &fake, container, "big.parquet"))
            .expect("install foreign objects");

        let total = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_rg")
            .expect("count query")
            .expect("count not null");
        assert_eq!(total, 12, "3 row-groups x 4 rows = 12");

        let filtered = Spi::get_one::<i64>("SELECT COUNT(*) FROM events_rg WHERE id > 100")
            .expect("count query")
            .expect("count not null");
        assert_eq!(filtered, 7, "ids 101..103 + 200..203 = 7 rows");
    }

    // ---------------------------------------------------------------------
    // Live Azure smoke test (Task 22).
    //
    // OPT-IN: This `#[pg_test]` runs against a REAL Azure storage container
    // when the `AZURE_TEST_SAS_URL` environment variable is set to a full
    // container SAS URL of the form
    //   `https://<account>.blob.core.windows.net/<container>?<sas-querystring>`
    // with at least `racwl` permissions (read, add, create, write, list).
    //
    // Without the env var the test is a no-op early-return so CI without
    // the secret is a pass. The SAS URL is parsed to extract the account
    // and container; the `endpoint` SERVER option is a no-op placeholder
    // for the SasUrl auth path (the full pre-signed URL carries everything
    // we need) but is still required by the SERVER options validator.
    //
    // CLEANUP: each invocation uses a unique `smoke-<uuid>/` blob prefix so
    // concurrent runs don't collide. We do NOT delete blobs at end of test
    // (the FDW has no DELETE path); the prefix is printed so a human can
    // clean up via `az storage blob delete-batch` if desired.
    fn parse_sas_url(url: &str) -> Option<(String, String, String)> {
        let u = url::Url::parse(url).ok()?;
        let host = u.host_str()?;
        let account = host.split('.').next()?.to_string();
        let path = u.path().trim_start_matches('/');
        let container = path.split('/').next()?.to_string();
        if account.is_empty() || container.is_empty() {
            return None;
        }
        Some((account, container, url.to_string()))
    }

    #[pg_test]
    fn live_smoke_write_then_read() {
        let Some((account, container, sas)) = std::env::var("AZURE_TEST_SAS_URL")
            .ok()
            .and_then(|s| parse_sas_url(&s))
        else {
            eprintln!("AZURE_TEST_SAS_URL not set; skipping live Azure smoke test");
            return;
        };

        let prefix = format!("smoke-{}", uuid::Uuid::new_v4());
        eprintln!(
            "live_smoke: account={account} container={container} prefix={prefix} \
             (blobs will be left in place; clean up manually if needed)"
        );

        let write_filename = format!("{prefix}/*");
        let read_filename = format!("{prefix}/*.parquet");

        Spi::run(&format!(
            r#"
            DROP FOREIGN TABLE IF EXISTS live_w CASCADE;
            DROP FOREIGN TABLE IF EXISTS live_r CASCADE;
            DROP USER MAPPING IF EXISTS FOR CURRENT_USER SERVER live_az;
            DROP SERVER IF EXISTS live_az CASCADE;

            CREATE SERVER live_az FOREIGN DATA WRAPPER parquet_azure_fdw
              OPTIONS (account_name '{account}',
                       endpoint 'blob.core.windows.net',
                       auth_method 'sas_url');
            CREATE USER MAPPING FOR CURRENT_USER SERVER live_az
              OPTIONS (sas_url '{sas}');
            CREATE FOREIGN TABLE live_w (id bigint, name text)
              SERVER live_az
              OPTIONS (container '{container}', filename '{write_filename}');
            CREATE FOREIGN TABLE live_r (id bigint, name text)
              SERVER live_az
              OPTIONS (container '{container}', filename '{read_filename}');
            INSERT INTO live_w VALUES (1,'alpha'),(2,'beta'),(3,'gamma');
            "#
        ))
        .expect("install + insert against live Azure");

        let count = Spi::get_one::<i64>("SELECT COUNT(*) FROM live_r WHERE id IN (1,2,3)")
            .expect("count query")
            .expect("count not null");
        assert_eq!(count, 3);
    }

    // ---------------------------------------------------------------------
    // End-to-end UPDATE / DELETE suite (Task 15).
    //
    // Each test:
    //   1. Seeds a container with a `data.parquet` of `(id bigint, name text)`
    //      via the harness `put_blob` + `build_simple_parquet` path.
    //   2. Wires SERVER / USER MAPPING / FOREIGN TABLE against that single
    //      blob (no glob — UPDATE/DELETE addresses fixed blob names).
    //   3. Drives the FDW via SPI and asserts via SELECT or, where the
    //      assertion is "no Azure I/O happened", via `read_etag` against
    //      the underlying blob.
    //
    // Schema-mapping note: `build_simple_parquet` produces parquet columns
    // named `id` (Int64) and `name` (Utf8). The foreign table's column
    // names are matched by name in `pg_attrs_to_arrow_schema`, so the
    // foreign table column names must match the parquet column names.

    #[cfg(feature = "pg_test")]
    fn install_modify_objects_sql(suffix: &str, fake: &FakeBlobStore, container: &str) -> String {
        let sas = fake.sas_url(container);
        format!(
            r#"
            DROP FOREIGN TABLE IF EXISTS mod_{suffix} CASCADE;
            DROP USER MAPPING IF EXISTS FOR CURRENT_USER SERVER azm_{suffix};
            DROP SERVER IF EXISTS azm_{suffix} CASCADE;

            CREATE SERVER azm_{suffix} FOREIGN DATA WRAPPER parquet_azure_fdw
              OPTIONS (account_name 'fakeaccount',
                       endpoint 'blob.core.windows.net',
                       auth_method 'sas_url');
            CREATE USER MAPPING FOR CURRENT_USER SERVER azm_{suffix}
              OPTIONS (sas_url '{sas}');
            CREATE FOREIGN TABLE mod_{suffix} (id bigint, name text)
              SERVER azm_{suffix}
              OPTIONS (container '{container}', filename 'data.parquet');
            "#
        )
    }

    /// Seed a fresh fake container with a known two-row `data.parquet` and
    /// install the foreign-table SQL stack. Returns the fake so each test
    /// can use it for direct etag/blob inspection.
    #[cfg(feature = "pg_test")]
    fn setup_two_row_modify(suffix: &str, container: &str) -> FakeBlobStore {
        let fake = FakeBlobStore::start_blocking();
        let bytes = build_simple_parquet(&[1, 2], &["a", "b"]);
        fake.put_blob(container, "data.parquet", bytes);
        Spi::run(&install_modify_objects_sql(suffix, &fake, container))
            .expect("install foreign objects");
        fake
    }

    // HISTORICAL (T15): the COMMIT path of these tests once produced a
    // SIGABRT inside `commit_plan` because we relied on the executor's
    // `tts_tid` field, which the planner does not always populate. T15's fix
    // (`add_row_identity_var` + a resjunk `ctid` junk-attribute fetched in
    // `exec_foreign_{update,delete}`) eliminated the crash, and every
    // single-process test below now runs unignored. The one remaining
    // `#[ignore]` is `pg_update_serialization_failure`, which models a
    // *concurrent* update from a second backend — pgrx's single-process
    // test harness can't drive two backends, so we cover that path via the
    // wiremock-based `tests/update_delete.rs::etag_conflict_returns_*` cases
    // and leave the pg_test stub in place for the day we add a multi-backend
    // harness.

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_update_basic() {
        let container = "pg-upd-basic";
        let _fake = setup_two_row_modify("upd_basic", container);

        Spi::run("UPDATE mod_upd_basic SET name = 'new' WHERE id = 1").unwrap();
        let v: Option<String> =
            Spi::get_one("SELECT name FROM mod_upd_basic WHERE id = 1").unwrap();
        assert_eq!(v.as_deref(), Some("new"));

        // Untouched row still present with original value.
        let v2: Option<String> =
            Spi::get_one("SELECT name FROM mod_upd_basic WHERE id = 2").unwrap();
        assert_eq!(v2.as_deref(), Some("b"));
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_delete_basic() {
        let container = "pg-del-basic";
        let _fake = setup_two_row_modify("del_basic", container);

        Spi::run("DELETE FROM mod_del_basic WHERE id = 1").unwrap();
        let n: Option<i64> = Spi::get_one("SELECT count(*)::bigint FROM mod_del_basic").unwrap();
        assert_eq!(n, Some(1));

        // The surviving row is the one we didn't target.
        let surviving: Option<i64> = Spi::get_one("SELECT id FROM mod_del_basic").unwrap();
        assert_eq!(surviving, Some(2));
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_update_returning_echoes_new_value() {
        let container = "pg-upd-ret";
        let _fake = setup_two_row_modify("upd_ret", container);

        let v: Option<String> =
            Spi::get_one("UPDATE mod_upd_ret SET name = 'r' WHERE id = 2 RETURNING name").unwrap();
        assert_eq!(v.as_deref(), Some("r"));
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_delete_where_false_is_noop() {
        // DELETE matching zero rows must produce ZERO Azure I/O — the
        // accumulator stays empty so `commit_plan` never enters its
        // per-blob GET/PUT loop, and the blob's etag is unchanged.
        let container = "pg-del-false";
        let fake = setup_two_row_modify("del_false", container);

        let pre_etag = fake
            .read_etag(container, "data.parquet")
            .expect("blob exists pre");

        Spi::run("DELETE FROM mod_del_false WHERE id = 99").unwrap();

        let post_etag = fake
            .read_etag(container, "data.parquet")
            .expect("blob exists post");
        assert_eq!(
            pre_etag, post_etag,
            "no rows matched — no Azure I/O expected"
        );

        // Row count unchanged.
        let n: Option<i64> = Spi::get_one("SELECT count(*)::bigint FROM mod_del_false").unwrap();
        assert_eq!(n, Some(2));
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_rollback_discards_pending_edits() {
        // BEGIN; UPDATE; ROLLBACK; — `end_foreign_modify` sees
        // `IsAbortedTransactionBlockState()` and must skip `commit_plan`,
        // leaving the blob unchanged.
        //
        // As in the INSERT-side rollback test (`rollback_before_end_modify_drops_buffer`),
        // BEGIN/UPDATE/ROLLBACK must be executed as a single SPI batch — issuing
        // them as separate `Spi::run` calls wraps each in its own subtransaction
        // and the BEGIN/ROLLBACK pair becomes a no-op.
        let container = "pg-rb";
        let fake = setup_two_row_modify("rb", container);

        let pre_etag = fake
            .read_etag(container, "data.parquet")
            .expect("blob exists pre");

        let r = Spi::run(
            "BEGIN; \
             UPDATE mod_rb SET name = 'z' WHERE id = 1; \
             ROLLBACK;",
        );
        let _ = r; // ROLLBACK may surface as an Spi error in some pgrx versions.

        let post_etag = fake
            .read_etag(container, "data.parquet")
            .expect("blob exists post");
        assert_eq!(
            pre_etag, post_etag,
            "ROLLBACK must not commit edits to the blob"
        );

        // And a fresh SELECT sees the original row, not the rolled-back edit.
        let v: Option<String> = Spi::get_one("SELECT name FROM mod_rb WHERE id = 1").unwrap();
        assert_eq!(v.as_deref(), Some("a"));
    }

    /// Concurrent serialization-failure — end-to-end through the FDW's
    /// `commit_plan`.
    ///
    /// The SQL harness (`pgrx test`) is single-process / single-session,
    /// so we cannot drive a concurrent SQL writer between `begin_foreign_scan`
    /// and `end_foreign_modify` of the *same* UPDATE statement. Instead, the
    /// full wiring is covered by the integration test
    /// `tests/update_delete.rs::scan_handoff_to_commit_plan_lost_update_guard`,
    /// which:
    ///
    /// 1. publishes a real scan-time handoff via `scan_handoff::publish`,
    /// 2. drives `commit_plan` directly against the wiremock fake,
    /// 3. overwrites the blob out-of-band to bump its ETag,
    /// 4. asserts the resulting error is `FdwError::ConcurrentUpdate`
    ///    (which `error::raise` maps to SQLSTATE 40001).
    ///
    /// The lower-level Azure-API mapping (412 → `ConcurrentUpdate`) is in
    /// turn covered by `concurrent_etag_conflict_returns_serialization_failure`.
    /// Together those two tests fence the load-bearing invariant from both
    /// ends: the wire mapping AND the full plan→commit plumbing.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    #[ignore]
    fn pg_update_serialization_failure() {
        // Intentionally empty — see doc-comment for the rationale and for
        // the integration-test coverage that fences the same invariant.
    }

    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn pg_update_then_select() {
        // Same session: UPDATE then SELECT. The FDW must NOT cache stale
        // blob bytes across statements — the second statement issues a
        // fresh GET against the fake and sees the new etag/body.
        let container = "pg-upd-then-sel";
        let _fake = setup_two_row_modify("upd_then_sel", container);

        Spi::run("UPDATE mod_upd_then_sel SET name = 'fresh' WHERE id = 1").unwrap();
        let v: Option<String> =
            Spi::get_one("SELECT name FROM mod_upd_then_sel WHERE id = 1").unwrap();
        assert_eq!(v.as_deref(), Some("fresh"));

        // And a follow-up UPDATE on the other row works on top of the
        // first one's committed state.
        Spi::run("UPDATE mod_upd_then_sel SET name = 'also' WHERE id = 2").unwrap();
        let v2: Option<String> =
            Spi::get_one("SELECT name FROM mod_upd_then_sel WHERE id = 2").unwrap();
        assert_eq!(v2.as_deref(), Some("also"));
        // The earlier edit must persist.
        let v1: Option<String> =
            Spi::get_one("SELECT name FROM mod_upd_then_sel WHERE id = 1").unwrap();
        assert_eq!(v1.as_deref(), Some("fresh"));
    }

    /// SP-3a Task 5: smoke test that `EXPLAIN` shows a `Gather` node for a
    /// parallel-safe foreign scan. This fences the wiring of the 5 parallel
    /// callbacks onto `FdwRoutine` AND the `add_partial_path` call in
    /// `get_foreign_paths` that allows the planner to consider them.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn parallel_scan_explain_shows_gather() {
        Spi::run("SET max_parallel_workers_per_gather = 2;").unwrap();
        Spi::run("SET min_parallel_table_scan_size = 0;").unwrap();
        Spi::run("SET parallel_setup_cost = 0;").unwrap();
        Spi::run("SET parallel_tuple_cost = 0;").unwrap();

        Spi::run(
            "CREATE SERVER parallel_smoke_srv FOREIGN DATA WRAPPER parquet_azure_fdw \
             OPTIONS (account_name 'devstoreaccount1', auth_method 'sas_url');",
        )
        .unwrap();
        Spi::run(
            "CREATE USER MAPPING FOR CURRENT_USER SERVER parallel_smoke_srv \
             OPTIONS (sas_url 'https://devstoreaccount1.blob.core.windows.net/parallel-smoke?sv=2024-11-04&sig=stub');",
        )
        .unwrap();
        Spi::run(
            "CREATE FOREIGN TABLE parallel_smoke_t (id int) \
             SERVER parallel_smoke_srv \
             OPTIONS (container 'parallel-smoke', filename 'data/*.parquet', parallel_workers '2');",
        )
        .unwrap();

        // Collect EXPLAIN output as one string. SpiTupleTable implements
        // Iterator yielding SpiHeapTupleData; column ordinals are 1-based.
        let plan: String = Spi::connect(|client| {
            let table = client
                .select(
                    "EXPLAIN (COSTS off) SELECT id FROM parallel_smoke_t;",
                    None,
                    &[],
                )
                .expect("explain");
            let mut lines: Vec<String> = Vec::new();
            for row in table {
                if let Ok(Some(s)) = row.get::<String>(1) {
                    lines.push(s);
                }
            }
            lines.join("\n")
        });

        assert!(
            plan.contains("Gather"),
            "EXPLAIN must show a Gather node; got plan:\n{plan}"
        );

        Spi::run("DROP FOREIGN TABLE parallel_smoke_t;").unwrap();
        Spi::run("DROP USER MAPPING FOR CURRENT_USER SERVER parallel_smoke_srv;").unwrap();
        Spi::run("DROP SERVER parallel_smoke_srv;").unwrap();
    }

    // -------------------------------------------------------------------
    // SP-3c sorted-merge `#[pg_test]` coverage. These drive REAL SELECTs
    // through the in-process wiremock fake (same wiring as the SELECT suite
    // above), so they exercise the scan-begin `build_state` sorted branch:
    // the same-type guard, the partitioned+sorted rejection, the C1
    // projection fix, and the planner's pathkey/EXPLAIN behaviour.
    // -------------------------------------------------------------------

    /// SQL that wires Server + UserMapping + a `(id BIGINT, name TEXT)`
    /// foreign table in `sorted 'id'` + `files_in_order 'true'` mode.
    #[cfg(feature = "pg_test")]
    fn install_sorted_objects_sql(
        suffix: &str,
        fake: &FakeBlobStore,
        container: &str,
        filename: &str,
    ) -> String {
        let sas = fake.sas_url(container);
        format!(
            r#"
            DROP FOREIGN TABLE IF EXISTS sorted_{suffix} CASCADE;
            DROP USER MAPPING IF EXISTS FOR CURRENT_USER SERVER sz_{suffix};
            DROP SERVER IF EXISTS sz_{suffix} CASCADE;

            CREATE SERVER sz_{suffix} FOREIGN DATA WRAPPER parquet_azure_fdw
              OPTIONS (account_name 'fakeaccount',
                       endpoint 'blob.core.windows.net',
                       auth_method 'sas_url');
            CREATE USER MAPPING FOR CURRENT_USER SERVER sz_{suffix}
              OPTIONS (sas_url '{sas}');
            CREATE FOREIGN TABLE sorted_{suffix} (id bigint, name text)
              SERVER sz_{suffix}
              OPTIONS (container '{container}', filename '{filename}',
                       sorted 'id', files_in_order 'true');
            "#
        )
    }

    /// SP-3c: a sorted-mode SELECT must merge multiple blobs into one globally
    /// ASC stream. Three blobs whose `id` ranges interleave (1/4/7, 2/5/8,
    /// 3/6/9) must come back fully merged. Also exercises the C1 projection
    /// fix indirectly (full row materialization under sorted mode).
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn sorted_select_merges_blobs_globally() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-sorted-merge";
        fake.put_blob(
            container,
            "s/a.parquet",
            build_simple_parquet(&[1, 4, 7], &["a", "d", "g"]),
        );
        fake.put_blob(
            container,
            "s/b.parquet",
            build_simple_parquet(&[2, 5, 8], &["b", "e", "h"]),
        );
        fake.put_blob(
            container,
            "s/c.parquet",
            build_simple_parquet(&[3, 6, 9], &["c", "f", "i"]),
        );

        Spi::run(&install_sorted_objects_sql(
            "merge",
            &fake,
            container,
            "s/*.parquet",
        ))
        .expect("install sorted objects");

        // string_agg with NO ORDER BY reflects the raw scan emission order;
        // sorted-mode must already produce globally-ascending rows.
        let ids: Option<String> =
            Spi::get_one("SELECT string_agg(id::text, ',') FROM sorted_merge").expect("agg");
        assert_eq!(ids.as_deref(), Some("1,2,3,4,5,6,7,8,9"));
    }

    /// SP-4: with `parquet_fdw.enable_multifile = off`, a table declared
    /// `sorted` must still return all rows correctly — via the sequential
    /// path (no K-way merge). Correctness is the binding assertion; the path
    /// switch itself is internal.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn enable_multifile_off_still_returns_rows() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-enable-multifile-off";
        fake.put_blob(
            container,
            "e/a.parquet",
            build_simple_parquet(&[1, 2, 3], &["a", "b", "c"]),
        );
        Spi::run("SET parquet_fdw.enable_multifile = off;").unwrap();
        Spi::run(&install_sorted_objects_sql(
            "mfoff",
            &fake,
            container,
            "e/*.parquet",
        ))
        .expect("install sorted objects");

        // All rows must come back (order not asserted — sequential path may
        // not be globally sorted across blobs without the merge).
        let n: Option<i64> = Spi::get_one("SELECT count(*) FROM sorted_mfoff").expect("count");
        assert_eq!(n, Some(3), "all rows must return with merge disabled");

        Spi::run("DROP FOREIGN TABLE sorted_mfoff;").unwrap();
        Spi::run("DROP USER MAPPING FOR CURRENT_USER SERVER sz_mfoff;").unwrap();
        Spi::run("DROP SERVER sz_mfoff;").unwrap();
        Spi::run("RESET parquet_fdw.enable_multifile;").unwrap();
    }

    /// SP-3c C1 REGRESSION: a projected SELECT that picks a proper subset /
    /// reorder of columns under sorted mode must return CORRECT values in each
    /// column (not swapped). Task 3 forced no-projection + identity attno_map
    /// in sorted mode; this guards against the swapped-column bug it fixed.
    ///
    /// We use a 3-column `(a BIGINT, b TEXT, c BIGINT)` table and
    /// `SELECT a, c ... ORDER BY a`, then assert the (a, c) pairs are the ones
    /// we authored — if a/c were mis-mapped, the c values would be wrong.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn sorted_projected_select_returns_correct_columns() {
        use arrow::array::{Array, Int64Array, RecordBatch, StringArray};
        use arrow::datatypes::{DataType, Field, Schema};
        use parquet::arrow::ArrowWriter;
        use parquet::file::properties::WriterProperties;
        use std::sync::Arc;

        // Build a 3-column blob: a=[1,3], b=["x","z"], c=[100,300].
        // c = a*100, so a swap of a/c is trivially detectable.
        fn three_col(a: &[i64], b: &[&str], c: &[i64]) -> bytes::Bytes {
            let schema = Arc::new(Schema::new(vec![
                Field::new("a", DataType::Int64, false),
                Field::new("b", DataType::Utf8, false),
                Field::new("c", DataType::Int64, false),
            ]));
            let batch = RecordBatch::try_new(
                schema.clone(),
                vec![
                    Arc::new(Int64Array::from(a.to_vec())) as Arc<dyn Array>,
                    Arc::new(StringArray::from(b.to_vec())),
                    Arc::new(Int64Array::from(c.to_vec())),
                ],
            )
            .unwrap();
            let mut buf: Vec<u8> = Vec::new();
            let mut w =
                ArrowWriter::try_new(&mut buf, schema, Some(WriterProperties::builder().build()))
                    .unwrap();
            w.write(&batch).unwrap();
            w.close().unwrap();
            bytes::Bytes::from(buf)
        }

        let fake = FakeBlobStore::start_blocking();
        let container = "test-sorted-proj";
        fake.put_blob(
            container,
            "p/a.parquet",
            three_col(&[1, 3], &["x", "z"], &[100, 300]),
        );
        fake.put_blob(
            container,
            "p/b.parquet",
            three_col(&[2, 4], &["y", "w"], &[200, 400]),
        );

        let sas = fake.sas_url(container);
        Spi::run(&format!(
            r#"
            CREATE SERVER sz_proj FOREIGN DATA WRAPPER parquet_azure_fdw
              OPTIONS (account_name 'fakeaccount', endpoint 'blob.core.windows.net',
                       auth_method 'sas_url');
            CREATE USER MAPPING FOR CURRENT_USER SERVER sz_proj
              OPTIONS (sas_url '{sas}');
            CREATE FOREIGN TABLE sorted_proj (a bigint, b text, c bigint)
              SERVER sz_proj
              OPTIONS (container '{container}', filename 'p/*.parquet',
                       sorted 'a', files_in_order 'true');
            "#
        ))
        .expect("install");

        // SELECT a, c (subset + drop b) ORDER BY a. c must equal a*100.
        let pairs: Option<String> = Spi::get_one(
            "SELECT string_agg(a::text || ':' || c::text, ',' ORDER BY a) FROM sorted_proj",
        )
        .expect("agg");
        assert_eq!(
            pairs.as_deref(),
            Some("1:100,2:200,3:300,4:400"),
            "projected (a, c) values must be correct (C1 regression)"
        );

        Spi::run("DROP FOREIGN TABLE sorted_proj;").unwrap();
        Spi::run("DROP USER MAPPING FOR CURRENT_USER SERVER sz_proj;").unwrap();
        Spi::run("DROP SERVER sz_proj;").unwrap();
    }

    // -------------------------------------------------------------------
    // DEFERRED scan-begin error coverage (same-type guard,
    // partitioned+sorted reject).
    //
    // Both guards live in `fdw::scan::build_state` and raise an
    // `FdwError::SchemaMismatch` via `error::raise` (a Postgres ereport
    // ERROR) from inside the raw `extern "C-unwind"` `begin_foreign_scan`
    // callback. Driving them from a `#[pg_test]` is NOT viable on this
    // harness: the ereport's C `siglongjmp` unwinds through the Rust scan
    // frames that still own the tokio runtime handle + `AzureBlobClient` +
    // open parquet streams, and the backend aborts (signal 6) before the
    // error can surface to the client as a recoverable `DbError`. Neither
    // `#[pg_test(error = ...)]` nor `Spi::run(...).expect_err` survives it —
    // the whole `SELECT tests.<fn>()` call crashes the backend. (Every
    // existing `#[pg_test(error = ...)]` in this file targets a CREATE-time
    // *validator* error, which is raised from a different callback that does
    // not have tokio/SDK state on the stack — those work; scan-begin ones do
    // not.)
    //
    // What IS covered instead:
    //   * The partitioned+sorted reject is a pure-logic guard
    //     (`if !core.partition_attnums.is_empty() { return Err(..) }`,
    //     scan.rs) executed before any row is produced; it has no I/O
    //     dependency and is exercised by manual / live (`cargo pgrx test
    //     pg14`) runs. NOTE: under `cargo pgrx test pg14` the same backend
    //     abort applies, so this remains a code-review + manual-SELECT
    //     assurance, not an automated assertion. Documented limitation.
    //   * The same-type guard's CORE CHECK — reading each blob's arrow
    //     schema and comparing the sort column's `DataType` across blobs —
    //     is reproduced and asserted directly against the fake blob store in
    //     `tests/multifile_sorted.rs::same_type_guard_detects_mismatched_sort_col_type`
    //     (a plain `cargo test`, no executor, no ereport). That test exercises
    //     the exact comparison `build_state` performs; only the final
    //     `error::raise` plumbing is left to manual verification.
    // -------------------------------------------------------------------

    /// SP-3c EXPLAIN check (brief Step 3). Task 4 took the NULL-pathkeys
    /// fallback, so PG WILL add a Sort node above the sorted ForeignScan.
    /// The merge still produces globally-sorted output, so this asserts only
    /// the WEAK property: a ForeignScan node exists. The strong "no Sort node"
    /// assertion is left commented out — it is blocked on PathKey emission
    /// (a future SP) and would fail given Task 4's documented fallback.
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn sorted_explain_has_foreign_scan() {
        let fake = FakeBlobStore::start_blocking();
        let container = "test-sorted-explain";
        fake.put_blob(
            container,
            "e/a.parquet",
            build_simple_parquet(&[1, 2, 3], &["a", "b", "c"]),
        );

        Spi::run(&install_sorted_objects_sql(
            "explain",
            &fake,
            container,
            "e/*.parquet",
        ))
        .expect("install sorted objects");

        let plan: String = Spi::connect(|client| {
            let table = client
                .select(
                    "EXPLAIN (COSTS off) SELECT id FROM sorted_explain ORDER BY id;",
                    None,
                    &[],
                )
                .expect("explain");
            let mut lines: Vec<String> = Vec::new();
            for row in table {
                if let Ok(Some(s)) = row.get::<String>(1) {
                    lines.push(s);
                }
            }
            lines.join("\n")
        });

        // WEAK assertion: ForeignScan exists. The sorted merge yields
        // globally-sorted output regardless of pathkey emission.
        assert!(
            plan.contains("Foreign Scan"),
            "plan must contain a Foreign Scan; got:\n{plan}"
        );
        // STRONG assertion — BLOCKED on PathKey emission (future SP). Task 4
        // fell back to NULL pathkeys, so PG adds a Sort node above the scan.
        // Leave commented; uncommenting would fail today.
        // assert!(!plan.contains("Sort"), "Sort node above ForeignScan; pathkey emission failed:\n{plan}");

        Spi::run("DROP FOREIGN TABLE sorted_explain;").unwrap();
        Spi::run("DROP USER MAPPING FOR CURRENT_USER SERVER sz_explain;").unwrap();
        Spi::run("DROP SERVER sz_explain;").unwrap();
    }
}

#[cfg(test)]
pub mod pg_test {
    pub fn setup(_options: Vec<&str>) {}
    pub fn postgresql_conf_options() -> Vec<&'static str> {
        vec![]
    }
}
